# Generated by Django 2.2 on 2019-12-14 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='作者名称', max_length=32, verbose_name='作者名称')),
                ('email', models.EmailField(help_text='邮箱', max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(help_text='手机号', max_length=11, verbose_name='手机号')),
                ('city', models.CharField(blank=True, help_text='城市', max_length=100, null=True, verbose_name='城市')),
                ('address', models.CharField(blank=True, help_text='作者地址', max_length=100, null=True, verbose_name='作者地址')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='出版商名称', max_length=32, verbose_name='出版商名称')),
                ('city', models.CharField(blank=True, help_text='出版商名称', max_length=32, null=True, verbose_name='出版商城市')),
                ('address', models.CharField(blank=True, help_text='出版商地址', max_length=32, null=True, verbose_name='出版商地址')),
            ],
            options={
                'verbose_name': '出版商',
                'verbose_name_plural': '出版商',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='书名', max_length=100, verbose_name='书名')),
                ('publication_date', models.DateTimeField(blank=True, help_text='出版时间', null=True, verbose_name='出版时间')),
                ('author', models.ManyToManyField(help_text='作者', to='books.Author', verbose_name='作者')),
                ('publisher', models.ForeignKey(help_text='出版商', on_delete=django.db.models.deletion.CASCADE, to='books.Publish', verbose_name='出版社')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
        ),
    ]
